// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: llmsvc.proto

package llmsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LlmSvc_Embed_FullMethodName           = "/llmsvc.LlmSvc/Embed"
	LlmSvc_Rerank_FullMethodName          = "/llmsvc.LlmSvc/Rerank"
	LlmSvc_ExtractEntities_FullMethodName = "/llmsvc.LlmSvc/ExtractEntities"
	LlmSvc_Compress_FullMethodName        = "/llmsvc.LlmSvc/Compress"
	LlmSvc_DetectIntent_FullMethodName    = "/llmsvc.LlmSvc/DetectIntent"
	LlmSvc_Generate_FullMethodName        = "/llmsvc.LlmSvc/Generate"
	LlmSvc_Health_FullMethodName          = "/llmsvc.LlmSvc/Health"
	LlmSvc_ListModels_FullMethodName      = "/llmsvc.LlmSvc/ListModels"
)

// LlmSvcClient is the client API for LlmSvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LlmSvc is the unified gRPC service for all LLM-related computation:
// embedding, reranking, entity/relationship extraction (NER),
// context compression, intent detection, and answer generation.
// Go backend (m365-knowledge-graph) never makes direct LLM provider calls;
// all LLM operations route through this gRPC service.
type LlmSvcClient interface {
	// Embed generates embeddings for a batch of texts.
	Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error)
	// Rerank scores a set of documents/chunks against a query.
	Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error)
	// ExtractEntities performs NLP entity and relationship extraction.
	// Used both at ingestion time (extracting from document chunks)
	// and at query time (extracting entities from the user's question).
	ExtractEntities(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error)
	// Compress reduces context size using map-reduce or abstractive summarization.
	// Called at retrieval Stage 6 if packed context exceeds token budget.
	Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error)
	// DetectIntent classifies the user's intent (find_expert, find_document, etc.).
	// Called at retrieval Stage 1.
	DetectIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error)
	// Generate produces an answer to a user query.
	// Called at retrieval Stage 7; may route to local model or cloud proxy per NLP_MODE.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error)
	// Health checks the service's liveness.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// ListModels returns available embedding and generative models.
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type llmSvcClient struct {
	cc grpc.ClientConnInterface
}

func NewLlmSvcClient(cc grpc.ClientConnInterface) LlmSvcClient {
	return &llmSvcClient{cc}
}

func (c *llmSvcClient) Embed(ctx context.Context, in *EmbedRequest, opts ...grpc.CallOption) (*EmbedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedResponse)
	err := c.cc.Invoke(ctx, LlmSvc_Embed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) Rerank(ctx context.Context, in *RerankRequest, opts ...grpc.CallOption) (*RerankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RerankResponse)
	err := c.cc.Invoke(ctx, LlmSvc_Rerank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) ExtractEntities(ctx context.Context, in *ExtractRequest, opts ...grpc.CallOption) (*ExtractResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractResponse)
	err := c.cc.Invoke(ctx, LlmSvc_ExtractEntities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) Compress(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompressResponse)
	err := c.cc.Invoke(ctx, LlmSvc_Compress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) DetectIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntentResponse)
	err := c.cc.Invoke(ctx, LlmSvc_DetectIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (*GenerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateResponse)
	err := c.cc.Invoke(ctx, LlmSvc_Generate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LlmSvc_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *llmSvcClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, LlmSvc_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LlmSvcServer is the server API for LlmSvc service.
// All implementations must embed UnimplementedLlmSvcServer
// for forward compatibility.
//
// LlmSvc is the unified gRPC service for all LLM-related computation:
// embedding, reranking, entity/relationship extraction (NER),
// context compression, intent detection, and answer generation.
// Go backend (m365-knowledge-graph) never makes direct LLM provider calls;
// all LLM operations route through this gRPC service.
type LlmSvcServer interface {
	// Embed generates embeddings for a batch of texts.
	Embed(context.Context, *EmbedRequest) (*EmbedResponse, error)
	// Rerank scores a set of documents/chunks against a query.
	Rerank(context.Context, *RerankRequest) (*RerankResponse, error)
	// ExtractEntities performs NLP entity and relationship extraction.
	// Used both at ingestion time (extracting from document chunks)
	// and at query time (extracting entities from the user's question).
	ExtractEntities(context.Context, *ExtractRequest) (*ExtractResponse, error)
	// Compress reduces context size using map-reduce or abstractive summarization.
	// Called at retrieval Stage 6 if packed context exceeds token budget.
	Compress(context.Context, *CompressRequest) (*CompressResponse, error)
	// DetectIntent classifies the user's intent (find_expert, find_document, etc.).
	// Called at retrieval Stage 1.
	DetectIntent(context.Context, *IntentRequest) (*IntentResponse, error)
	// Generate produces an answer to a user query.
	// Called at retrieval Stage 7; may route to local model or cloud proxy per NLP_MODE.
	Generate(context.Context, *GenerateRequest) (*GenerateResponse, error)
	// Health checks the service's liveness.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// ListModels returns available embedding and generative models.
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedLlmSvcServer()
}

// UnimplementedLlmSvcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLlmSvcServer struct{}

func (UnimplementedLlmSvcServer) Embed(context.Context, *EmbedRequest) (*EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Embed not implemented")
}
func (UnimplementedLlmSvcServer) Rerank(context.Context, *RerankRequest) (*RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rerank not implemented")
}
func (UnimplementedLlmSvcServer) ExtractEntities(context.Context, *ExtractRequest) (*ExtractResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractEntities not implemented")
}
func (UnimplementedLlmSvcServer) Compress(context.Context, *CompressRequest) (*CompressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compress not implemented")
}
func (UnimplementedLlmSvcServer) DetectIntent(context.Context, *IntentRequest) (*IntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectIntent not implemented")
}
func (UnimplementedLlmSvcServer) Generate(context.Context, *GenerateRequest) (*GenerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedLlmSvcServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLlmSvcServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLlmSvcServer) mustEmbedUnimplementedLlmSvcServer() {}
func (UnimplementedLlmSvcServer) testEmbeddedByValue()                {}

// UnsafeLlmSvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LlmSvcServer will
// result in compilation errors.
type UnsafeLlmSvcServer interface {
	mustEmbedUnimplementedLlmSvcServer()
}

func RegisterLlmSvcServer(s grpc.ServiceRegistrar, srv LlmSvcServer) {
	// If the following call panics, it indicates UnimplementedLlmSvcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LlmSvc_ServiceDesc, srv)
}

func _LlmSvc_Embed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).Embed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_Embed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).Embed(ctx, req.(*EmbedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_Rerank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RerankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).Rerank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_Rerank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).Rerank(ctx, req.(*RerankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_ExtractEntities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).ExtractEntities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_ExtractEntities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).ExtractEntities(ctx, req.(*ExtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_Compress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).Compress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_Compress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).Compress(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_DetectIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).DetectIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_DetectIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).DetectIntent(ctx, req.(*IntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_Generate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).Generate(ctx, req.(*GenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LlmSvc_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LlmSvcServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LlmSvc_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LlmSvcServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LlmSvc_ServiceDesc is the grpc.ServiceDesc for LlmSvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LlmSvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmsvc.LlmSvc",
	HandlerType: (*LlmSvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Embed",
			Handler:    _LlmSvc_Embed_Handler,
		},
		{
			MethodName: "Rerank",
			Handler:    _LlmSvc_Rerank_Handler,
		},
		{
			MethodName: "ExtractEntities",
			Handler:    _LlmSvc_ExtractEntities_Handler,
		},
		{
			MethodName: "Compress",
			Handler:    _LlmSvc_Compress_Handler,
		},
		{
			MethodName: "DetectIntent",
			Handler:    _LlmSvc_DetectIntent_Handler,
		},
		{
			MethodName: "Generate",
			Handler:    _LlmSvc_Generate_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LlmSvc_Health_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LlmSvc_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmsvc.proto",
}
