// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: llmsvc.proto

package llmsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// texts: list of text snippets to embed (e.g., document chunks, search queries)
	Texts []string `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	// model_name: embedding model identifier (e.g., "text-embedding-3-small", "e5-large-v2")
	// If empty, service uses default embedding model configured in models.yaml
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// task_type: semantic task hint (optional, for multi-task models):
	// "search_document", "search_query", "classify", "clustering"
	TaskType      string `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_llmsvc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *EmbedRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbedRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type EmbedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// embeddings: one embedding (as float32 array, serialized as bytes) per input text
	Embeddings [][]byte `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	// model_name: echo back the model used
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// dimensions: vector dimensionality (e.g., 384, 1536)
	Dimensions int32 `protobuf:"varint,3,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// error: populated if the request failed (e.g., invalid model, service error)
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_llmsvc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetEmbeddings() [][]byte {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

func (x *EmbedResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbedResponse) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *EmbedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RerankRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query: the reference query text (user's question or intent)
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// documents: candidate documents/chunks to score against the query
	Documents []*RerankDocument `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	// model_name: reranking model (e.g., "bge-reranker-base", "ms-marco-minilm-l-12-v2")
	// If empty, service uses default reranker configured in models.yaml
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// top_k: optional, limit output to top-k results (0 = all)
	TopK          int32 `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankRequest) Reset() {
	*x = RerankRequest{}
	mi := &file_llmsvc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankRequest) ProtoMessage() {}

func (x *RerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankRequest.ProtoReflect.Descriptor instead.
func (*RerankRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{2}
}

func (x *RerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankRequest) GetDocuments() []*RerankDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type RerankDocument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// doc_id: unique identifier for this document (e.g., chunk ID, entity ID)
	DocId string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// text: document/chunk content to score
	Text string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// metadata: optional JSON-encoded metadata for logging/debugging
	Metadata      string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankDocument) Reset() {
	*x = RerankDocument{}
	mi := &file_llmsvc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankDocument) ProtoMessage() {}

func (x *RerankDocument) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankDocument.ProtoReflect.Descriptor instead.
func (*RerankDocument) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{3}
}

func (x *RerankDocument) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *RerankDocument) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RerankDocument) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type RerankResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results: scored documents, sorted by score descending
	Results []*RerankResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// model_name: echo back the model used
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// error: populated if the request failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResponse) Reset() {
	*x = RerankResponse{}
	mi := &file_llmsvc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResponse) ProtoMessage() {}

func (x *RerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResponse.ProtoReflect.Descriptor instead.
func (*RerankResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{4}
}

func (x *RerankResponse) GetResults() []*RerankResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RerankResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *RerankResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RerankResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// doc_id: from RerankDocument
	DocId string `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// score: relevance score (typically 0.0–1.0, higher = more relevant)
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	// rank: result rank (1-indexed, after sorting)
	Rank          int32 `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankResult) Reset() {
	*x = RerankResult{}
	mi := &file_llmsvc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankResult) ProtoMessage() {}

func (x *RerankResult) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankResult.ProtoReflect.Descriptor instead.
func (*RerankResult) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{5}
}

func (x *RerankResult) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *RerankResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RerankResult) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ExtractRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text: input text to extract entities and relationships from
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// task_mode: "ingestion" (extract from document) or "query" (extract from user question)
	// Affects the extraction prompts and entity types considered
	TaskMode string `protobuf:"bytes,2,opt,name=task_mode,json=taskMode,proto3" json:"task_mode,omitempty"`
	// model_name: LLM model for extraction
	// If empty, service uses default configured model (per NLP_MODE)
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// schema: optional JSON schema for entity types / relationship types to extract
	// If empty, uses a default business-domain schema (Person, Project, Document, Technology, etc.)
	Schema string `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	// include_relationships: if true, also extract relationships between entities
	IncludeRelationships bool `protobuf:"varint,5,opt,name=include_relationships,json=includeRelationships,proto3" json:"include_relationships,omitempty"`
	// task_type: Brain task-tagging hint (e.g., "nlp_extraction", "query_ner")
	// used by llm-svc's routing.rs to decide local vs. cloud per NLP_MODE
	TaskType      string `protobuf:"bytes,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractRequest) Reset() {
	*x = ExtractRequest{}
	mi := &file_llmsvc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractRequest) ProtoMessage() {}

func (x *ExtractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractRequest.ProtoReflect.Descriptor instead.
func (*ExtractRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{6}
}

func (x *ExtractRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ExtractRequest) GetTaskMode() string {
	if x != nil {
		return x.TaskMode
	}
	return ""
}

func (x *ExtractRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ExtractRequest) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ExtractRequest) GetIncludeRelationships() bool {
	if x != nil {
		return x.IncludeRelationships
	}
	return false
}

func (x *ExtractRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type Entity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: entity text
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type: entity type (e.g., "Person", "Project", "Technology")
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// confidence: confidence score 0.0–1.0
	Confidence float32 `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// metadata: optional JSON metadata (e.g., span offsets, attributes)
	Metadata      string `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_llmsvc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{7}
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Entity) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type Relationship struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// from_entity: source entity identifier or text
	FromEntity string `protobuf:"bytes,1,opt,name=from_entity,json=fromEntity,proto3" json:"from_entity,omitempty"`
	// relationship_type: e.g., "works_on", "manages", "uses"
	RelationshipType string `protobuf:"bytes,2,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	// to_entity: target entity identifier or text
	ToEntity string `protobuf:"bytes,3,opt,name=to_entity,json=toEntity,proto3" json:"to_entity,omitempty"`
	// confidence: confidence 0.0–1.0
	Confidence float32 `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// metadata: optional JSON metadata
	Metadata      string `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_llmsvc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{8}
}

func (x *Relationship) GetFromEntity() string {
	if x != nil {
		return x.FromEntity
	}
	return ""
}

func (x *Relationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Relationship) GetToEntity() string {
	if x != nil {
		return x.ToEntity
	}
	return ""
}

func (x *Relationship) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Relationship) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type ExtractResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// entities: extracted entities
	Entities []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	// relationships: extracted relationships
	Relationships []*Relationship `protobuf:"bytes,2,rep,name=relationships,proto3" json:"relationships,omitempty"`
	// model_name: echo back the model used
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// error: populated if extraction failed
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractResponse) Reset() {
	*x = ExtractResponse{}
	mi := &file_llmsvc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractResponse) ProtoMessage() {}

func (x *ExtractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractResponse.ProtoReflect.Descriptor instead.
func (*ExtractResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{9}
}

func (x *ExtractResponse) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ExtractResponse) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *ExtractResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ExtractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// context: full context (assembled from retrieval Stage 5)
	// that may exceed token budget
	Context string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// target_tokens: desired max token count after compression (e.g., 8000)
	TargetTokens int32 `protobuf:"varint,2,opt,name=target_tokens,json=targetTokens,proto3" json:"target_tokens,omitempty"`
	// method: compression strategy
	// "map_reduce" = split into chunks, summarize each, join summaries
	// "abstractive" = LLM-based abstractive summarization
	// "extract" = extractive summarization (keep top sentences)
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// query: optional query hint to bias compression
	Query string `protobuf:"bytes,4,opt,name=query,proto3" json:"query,omitempty"`
	// model_name: LLM for compression (only used if method="abstractive")
	ModelName string `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// task_type: Brain task-tagging hint (e.g., "context_compression")
	// used by llm-svc's routing.rs to decide local vs. cloud per NLP_MODE
	TaskType      string `protobuf:"bytes,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressRequest) Reset() {
	*x = CompressRequest{}
	mi := &file_llmsvc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressRequest) ProtoMessage() {}

func (x *CompressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressRequest.ProtoReflect.Descriptor instead.
func (*CompressRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{10}
}

func (x *CompressRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CompressRequest) GetTargetTokens() int32 {
	if x != nil {
		return x.TargetTokens
	}
	return 0
}

func (x *CompressRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CompressRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CompressRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *CompressRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type CompressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// compressed_context: compressed context string
	CompressedContext string `protobuf:"bytes,1,opt,name=compressed_context,json=compressedContext,proto3" json:"compressed_context,omitempty"`
	// original_tokens: estimated token count of input
	OriginalTokens int32 `protobuf:"varint,2,opt,name=original_tokens,json=originalTokens,proto3" json:"original_tokens,omitempty"`
	// compressed_tokens: estimated token count of output
	CompressedTokens int32 `protobuf:"varint,3,opt,name=compressed_tokens,json=compressedTokens,proto3" json:"compressed_tokens,omitempty"`
	// compression_ratio: compressed_tokens / original_tokens
	CompressionRatio float32 `protobuf:"fixed32,4,opt,name=compression_ratio,json=compressionRatio,proto3" json:"compression_ratio,omitempty"`
	// error: populated if compression failed
	Error         string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompressResponse) Reset() {
	*x = CompressResponse{}
	mi := &file_llmsvc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompressResponse) ProtoMessage() {}

func (x *CompressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompressResponse.ProtoReflect.Descriptor instead.
func (*CompressResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{11}
}

func (x *CompressResponse) GetCompressedContext() string {
	if x != nil {
		return x.CompressedContext
	}
	return ""
}

func (x *CompressResponse) GetOriginalTokens() int32 {
	if x != nil {
		return x.OriginalTokens
	}
	return 0
}

func (x *CompressResponse) GetCompressedTokens() int32 {
	if x != nil {
		return x.CompressedTokens
	}
	return 0
}

func (x *CompressResponse) GetCompressionRatio() float32 {
	if x != nil {
		return x.CompressionRatio
	}
	return 0
}

func (x *CompressResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IntentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query: user's natural language question
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// model_name: optional model override
	ModelName string `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// context: optional context to help intent classification
	Context string `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	// task_type: Brain task-tagging hint (e.g., "intent_detection")
	// used by llm-svc's routing.rs to decide local vs. cloud per NLP_MODE
	TaskType      string `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentRequest) Reset() {
	*x = IntentRequest{}
	mi := &file_llmsvc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentRequest) ProtoMessage() {}

func (x *IntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentRequest.ProtoReflect.Descriptor instead.
func (*IntentRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{12}
}

func (x *IntentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *IntentRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *IntentRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *IntentRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type IntentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// intent: detected intent type
	// Examples: "find_expert", "find_document", "find_project_info",
	// "find_technology_usage", "general_question"
	Intent string `protobuf:"bytes,1,opt,name=intent,proto3" json:"intent,omitempty"`
	// confidence: confidence 0.0–1.0
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// attributes: optional JSON map of extracted intent attributes
	// (e.g., {"entity_type": "person", "action": "find"})
	Attributes string `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// error: populated if intent detection failed
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentResponse) Reset() {
	*x = IntentResponse{}
	mi := &file_llmsvc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentResponse) ProtoMessage() {}

func (x *IntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentResponse.ProtoReflect.Descriptor instead.
func (*IntentResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{13}
}

func (x *IntentResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *IntentResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *IntentResponse) GetAttributes() string {
	if x != nil {
		return x.Attributes
	}
	return ""
}

func (x *IntentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// query: user's original question
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// context: assembled, compressed context from retrieval Stage 6
	Context string `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	// instructions: optional system prompt / generation instructions
	Instructions string `protobuf:"bytes,3,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// temperature: LLM sampling parameter (0.0–2.0, default 0.7)
	Temperature float32 `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	// max_tokens: max output length in tokens (default 2048)
	MaxTokens int32 `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	// model_name: optional model override
	ModelName string `protobuf:"bytes,6,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// include_citations: if true, answer includes source citations
	IncludeCitations bool `protobuf:"varint,7,opt,name=include_citations,json=includeCitations,proto3" json:"include_citations,omitempty"`
	// task_type: Brain task-tagging hint (e.g., "answer_generation")
	// used by llm-svc's routing.rs to decide local vs. cloud per NLP_MODE
	TaskType      string `protobuf:"bytes,8,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_llmsvc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GenerateRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GenerateRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GenerateRequest) GetIncludeCitations() bool {
	if x != nil {
		return x.IncludeCitations
	}
	return false
}

func (x *GenerateRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// answer: generated answer text
	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	// citations: list of cited sources (chunk IDs, document names, URLs)
	Citations []string `protobuf:"bytes,2,rep,name=citations,proto3" json:"citations,omitempty"`
	// model_name: echo back the model used
	ModelName string `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	// tokens_used: estimated token count of the generated answer
	TokensUsed int32 `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	// latency_ms: service-side processing time in milliseconds
	LatencyMs int32 `protobuf:"varint,5,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// error: populated if generation failed
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_llmsvc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *GenerateResponse) GetCitations() []string {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *GenerateResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GenerateResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *GenerateResponse) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *GenerateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// service: optional service name to check health of (e.g., "llmsvc.LlmSvc")
	// If empty, checks overall service health
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_llmsvc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{16}
}

func (x *HealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status: health status ("SERVING", "NOT_SERVING", "UNKNOWN", "SERVICE_UNKNOWN")
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// message: optional human-readable details
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// checks: detailed status of sub-components
	Checks        map[string]string `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_llmsvc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{17}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetChecks() map[string]string {
	if x != nil {
		return x.Checks
	}
	return nil
}

type ListModelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model_kind: optional filter by kind ("embedding", "reranker", "generative")
	// If empty, returns all models
	ModelKind     string `protobuf:"bytes,1,opt,name=model_kind,json=modelKind,proto3" json:"model_kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_llmsvc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{18}
}

func (x *ListModelsRequest) GetModelKind() string {
	if x != nil {
		return x.ModelKind
	}
	return ""
}

type ListModelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// models: list of available models
	Models []*ModelInfo `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	// error: populated if listing failed
	Error         string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_llmsvc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{19}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ModelInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name: model identifier (e.g., "text-embedding-3-small", "qwen3-8b-q4")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// kind: model category ("embedding", "reranker", "generative", "other")
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// format: model format ("onnx", "gguf", "safetensors", "cloud")
	Format string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	// dimensions: for embedding models, vector dimensionality (0 for generative)
	Dimensions int32 `protobuf:"varint,4,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	// version: model version or revision
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// is_local: true if model is served locally in-process by llm-svc
	IsLocal bool `protobuf:"varint,6,opt,name=is_local,json=isLocal,proto3" json:"is_local,omitempty"`
	// is_default: true if this is the default model for its kind
	IsDefault bool `protobuf:"varint,7,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	// metadata: optional JSON-encoded additional metadata
	Metadata      string `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_llmsvc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_llmsvc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_llmsvc_proto_rawDescGZIP(), []int{20}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ModelInfo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ModelInfo) GetDimensions() int32 {
	if x != nil {
		return x.Dimensions
	}
	return 0
}

func (x *ModelInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelInfo) GetIsLocal() bool {
	if x != nil {
		return x.IsLocal
	}
	return false
}

func (x *ModelInfo) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ModelInfo) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

var File_llmsvc_proto protoreflect.FileDescriptor

const file_llmsvc_proto_rawDesc = "" +
	"\n" +
	"\fllmsvc.proto\x12\x06llmsvc\"`\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\"\x84\x01\n" +
	"\rEmbedResponse\x12\x1e\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\fR\n" +
	"embeddings\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x03 \x01(\x05R\n" +
	"dimensions\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8f\x01\n" +
	"\rRerankRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x124\n" +
	"\tdocuments\x18\x02 \x03(\v2\x16.llmsvc.RerankDocumentR\tdocuments\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\"W\n" +
	"\x0eRerankDocument\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\"u\n" +
	"\x0eRerankResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.llmsvc.RerankResultR\aresults\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"O\n" +
	"\fRerankResult\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\"\xca\x01\n" +
	"\x0eExtractRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\ttask_mode\x18\x02 \x01(\tR\btaskMode\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06schema\x18\x04 \x01(\tR\x06schema\x123\n" +
	"\x15include_relationships\x18\x05 \x01(\bR\x14includeRelationships\x12\x1b\n" +
	"\ttask_type\x18\x06 \x01(\tR\btaskType\"l\n" +
	"\x06Entity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\xb5\x01\n" +
	"\fRelationship\x12\x1f\n" +
	"\vfrom_entity\x18\x01 \x01(\tR\n" +
	"fromEntity\x12+\n" +
	"\x11relationship_type\x18\x02 \x01(\tR\x10relationshipType\x12\x1b\n" +
	"\tto_entity\x18\x03 \x01(\tR\btoEntity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\xae\x01\n" +
	"\x0fExtractResponse\x12*\n" +
	"\bentities\x18\x01 \x03(\v2\x0e.llmsvc.EntityR\bentities\x12:\n" +
	"\rrelationships\x18\x02 \x03(\v2\x14.llmsvc.RelationshipR\rrelationships\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xba\x01\n" +
	"\x0fCompressRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12#\n" +
	"\rtarget_tokens\x18\x02 \x01(\x05R\ftargetTokens\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x14\n" +
	"\x05query\x18\x04 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12\x1b\n" +
	"\ttask_type\x18\x06 \x01(\tR\btaskType\"\xda\x01\n" +
	"\x10CompressResponse\x12-\n" +
	"\x12compressed_context\x18\x01 \x01(\tR\x11compressedContext\x12'\n" +
	"\x0foriginal_tokens\x18\x02 \x01(\x05R\x0eoriginalTokens\x12+\n" +
	"\x11compressed_tokens\x18\x03 \x01(\x05R\x10compressedTokens\x12+\n" +
	"\x11compression_ratio\x18\x04 \x01(\x02R\x10compressionRatio\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"{\n" +
	"\rIntentRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\"~\n" +
	"\x0eIntentResponse\x12\x16\n" +
	"\x06intent\x18\x01 \x01(\tR\x06intent\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1e\n" +
	"\n" +
	"attributes\x18\x03 \x01(\tR\n" +
	"attributes\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8f\x02\n" +
	"\x0fGenerateRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x18\n" +
	"\acontext\x18\x02 \x01(\tR\acontext\x12\"\n" +
	"\finstructions\x18\x03 \x01(\tR\finstructions\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"model_name\x18\x06 \x01(\tR\tmodelName\x12+\n" +
	"\x11include_citations\x18\a \x01(\bR\x10includeCitations\x12\x1b\n" +
	"\ttask_type\x18\b \x01(\tR\btaskType\"\xbd\x01\n" +
	"\x10GenerateResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1c\n" +
	"\tcitations\x18\x02 \x03(\tR\tcitations\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x05 \x01(\x05R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\")\n" +
	"\rHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xb9\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x06checks\x18\x03 \x03(\v2\".llmsvc.HealthResponse.ChecksEntryR\x06checks\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x11ListModelsRequest\x12\x1d\n" +
	"\n" +
	"model_kind\x18\x01 \x01(\tR\tmodelKind\"U\n" +
	"\x12ListModelsResponse\x12)\n" +
	"\x06models\x18\x01 \x03(\v2\x11.llmsvc.ModelInfoR\x06models\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xdb\x01\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x04 \x01(\x05R\n" +
	"dimensions\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x19\n" +
	"\bis_local\x18\x06 \x01(\bR\aisLocal\x12\x1d\n" +
	"\n" +
	"is_default\x18\a \x01(\bR\tisDefault\x12\x1a\n" +
	"\bmetadata\x18\b \x01(\tR\bmetadata2\xf6\x03\n" +
	"\x06LlmSvc\x124\n" +
	"\x05Embed\x12\x14.llmsvc.EmbedRequest\x1a\x15.llmsvc.EmbedResponse\x127\n" +
	"\x06Rerank\x12\x15.llmsvc.RerankRequest\x1a\x16.llmsvc.RerankResponse\x12B\n" +
	"\x0fExtractEntities\x12\x16.llmsvc.ExtractRequest\x1a\x17.llmsvc.ExtractResponse\x12=\n" +
	"\bCompress\x12\x17.llmsvc.CompressRequest\x1a\x18.llmsvc.CompressResponse\x12=\n" +
	"\fDetectIntent\x12\x15.llmsvc.IntentRequest\x1a\x16.llmsvc.IntentResponse\x12=\n" +
	"\bGenerate\x12\x17.llmsvc.GenerateRequest\x1a\x18.llmsvc.GenerateResponse\x127\n" +
	"\x06Health\x12\x15.llmsvc.HealthRequest\x1a\x16.llmsvc.HealthResponse\x12C\n" +
	"\n" +
	"ListModels\x12\x19.llmsvc.ListModelsRequest\x1a\x1a.llmsvc.ListModelsResponseBW\n" +
	"\x0ecom.fpt.llmsvcP\x01Z:github.com/rad-system/m365-knowledge-graph/internal/llmsvc\xaa\x02\x06LlmSvcb\x06proto3"

var (
	file_llmsvc_proto_rawDescOnce sync.Once
	file_llmsvc_proto_rawDescData []byte
)

func file_llmsvc_proto_rawDescGZIP() []byte {
	file_llmsvc_proto_rawDescOnce.Do(func() {
		file_llmsvc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llmsvc_proto_rawDesc), len(file_llmsvc_proto_rawDesc)))
	})
	return file_llmsvc_proto_rawDescData
}

var file_llmsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_llmsvc_proto_goTypes = []any{
	(*EmbedRequest)(nil),       // 0: llmsvc.EmbedRequest
	(*EmbedResponse)(nil),      // 1: llmsvc.EmbedResponse
	(*RerankRequest)(nil),      // 2: llmsvc.RerankRequest
	(*RerankDocument)(nil),     // 3: llmsvc.RerankDocument
	(*RerankResponse)(nil),     // 4: llmsvc.RerankResponse
	(*RerankResult)(nil),       // 5: llmsvc.RerankResult
	(*ExtractRequest)(nil),     // 6: llmsvc.ExtractRequest
	(*Entity)(nil),             // 7: llmsvc.Entity
	(*Relationship)(nil),       // 8: llmsvc.Relationship
	(*ExtractResponse)(nil),    // 9: llmsvc.ExtractResponse
	(*CompressRequest)(nil),    // 10: llmsvc.CompressRequest
	(*CompressResponse)(nil),   // 11: llmsvc.CompressResponse
	(*IntentRequest)(nil),      // 12: llmsvc.IntentRequest
	(*IntentResponse)(nil),     // 13: llmsvc.IntentResponse
	(*GenerateRequest)(nil),    // 14: llmsvc.GenerateRequest
	(*GenerateResponse)(nil),   // 15: llmsvc.GenerateResponse
	(*HealthRequest)(nil),      // 16: llmsvc.HealthRequest
	(*HealthResponse)(nil),     // 17: llmsvc.HealthResponse
	(*ListModelsRequest)(nil),  // 18: llmsvc.ListModelsRequest
	(*ListModelsResponse)(nil), // 19: llmsvc.ListModelsResponse
	(*ModelInfo)(nil),          // 20: llmsvc.ModelInfo
	nil,                        // 21: llmsvc.HealthResponse.ChecksEntry
}
var file_llmsvc_proto_depIdxs = []int32{
	3,  // 0: llmsvc.RerankRequest.documents:type_name -> llmsvc.RerankDocument
	5,  // 1: llmsvc.RerankResponse.results:type_name -> llmsvc.RerankResult
	7,  // 2: llmsvc.ExtractResponse.entities:type_name -> llmsvc.Entity
	8,  // 3: llmsvc.ExtractResponse.relationships:type_name -> llmsvc.Relationship
	21, // 4: llmsvc.HealthResponse.checks:type_name -> llmsvc.HealthResponse.ChecksEntry
	20, // 5: llmsvc.ListModelsResponse.models:type_name -> llmsvc.ModelInfo
	0,  // 6: llmsvc.LlmSvc.Embed:input_type -> llmsvc.EmbedRequest
	2,  // 7: llmsvc.LlmSvc.Rerank:input_type -> llmsvc.RerankRequest
	6,  // 8: llmsvc.LlmSvc.ExtractEntities:input_type -> llmsvc.ExtractRequest
	10, // 9: llmsvc.LlmSvc.Compress:input_type -> llmsvc.CompressRequest
	12, // 10: llmsvc.LlmSvc.DetectIntent:input_type -> llmsvc.IntentRequest
	14, // 11: llmsvc.LlmSvc.Generate:input_type -> llmsvc.GenerateRequest
	16, // 12: llmsvc.LlmSvc.Health:input_type -> llmsvc.HealthRequest
	18, // 13: llmsvc.LlmSvc.ListModels:input_type -> llmsvc.ListModelsRequest
	1,  // 14: llmsvc.LlmSvc.Embed:output_type -> llmsvc.EmbedResponse
	4,  // 15: llmsvc.LlmSvc.Rerank:output_type -> llmsvc.RerankResponse
	9,  // 16: llmsvc.LlmSvc.ExtractEntities:output_type -> llmsvc.ExtractResponse
	11, // 17: llmsvc.LlmSvc.Compress:output_type -> llmsvc.CompressResponse
	13, // 18: llmsvc.LlmSvc.DetectIntent:output_type -> llmsvc.IntentResponse
	15, // 19: llmsvc.LlmSvc.Generate:output_type -> llmsvc.GenerateResponse
	17, // 20: llmsvc.LlmSvc.Health:output_type -> llmsvc.HealthResponse
	19, // 21: llmsvc.LlmSvc.ListModels:output_type -> llmsvc.ListModelsResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_llmsvc_proto_init() }
func file_llmsvc_proto_init() {
	if File_llmsvc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llmsvc_proto_rawDesc), len(file_llmsvc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmsvc_proto_goTypes,
		DependencyIndexes: file_llmsvc_proto_depIdxs,
		MessageInfos:      file_llmsvc_proto_msgTypes,
	}.Build()
	File_llmsvc_proto = out.File
	file_llmsvc_proto_goTypes = nil
	file_llmsvc_proto_depIdxs = nil
}
