/**
 * Docx OpenCode plugin bridge (issue #25 — agent-invocation wiring for the docx service).
 *
 * `DOCX_PLUGIN_SOURCE` is a STATIC string of TypeScript that runs inside OpenCode's in-process
 * Bun runtime (the pinned binary embeds Bun; a plugin file under `<configDir>/plugin/*.ts` is
 * loaded and executed directly). It must never contain a literal endpoint/token: both are read
 * from `process.env` at plugin-load time inside the child process, which the supervisor populates
 * per-launch. This keeps the loopback boundary, the token, and the tool surface entirely out of
 * any file/log the product writes.
 *
 * The exposed `create_docx` tool name MUST match `DOCX_TOOL_NAME` in
 * `../documents/docx-tool-router.ts` exactly — `service/tests/docx-tool-router.test.ts` asserts
 * this so router and plugin cannot drift.
 *
 * `writeDocxPlugin` mirrors the secret-refusal guard used by `writeMs365Plugin` /
 * `writeOpencodeConfig`: it accepts an optional `forbidden` value and refuses to write if the
 * serialized output unexpectedly contains it. Because the source here is a static template with
 * no interpolation, that branch should never trip — it exists as a regression guard rather than a
 * live code path. The `@opencode-ai/plugin` import resolves offline via `seedMs365PluginDeps`
 * (already invoked by the supervisor before this file is loaded).
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const DOCX_PLUGIN_SOURCE = `// AUTO-GENERATED by Cowork GHC — do not edit. Regenerated on every launch.
// Bridges OpenCode tool calls to the Cowork service docx boundary (loopback, scoped token).
import { tool } from "@opencode-ai/plugin";

const ENDPOINT = process.env["CGHC_DOCX_TOOL_ENDPOINT"];
const TOKEN = process.env["CGHC_DOCX_TOKEN"];

async function call(name, args, ctx) {
  if (!ENDPOINT || !TOKEN) {
    return JSON.stringify({ ok: false, error: { kind: "not_configured", message: "Docx tool bridge is not configured in this session." } });
  }
  try {
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-cowork-token": TOKEN },
      body: JSON.stringify({ name, args, sessionId: ctx.sessionID, requestId: crypto.randomUUID() }),
    });
    const body = await res.json();
    // Boundary envelope: { ok: true, data: DocxToolResult } | { ok: false, error: {...} }
    if (body && body.ok === true) return JSON.stringify(body.data);
    return JSON.stringify({ ok: false, error: { kind: "boundary_error", message: "Docx boundary returned HTTP " + res.status + "." } });
  } catch {
    return JSON.stringify({ ok: false, error: { kind: "network_error", message: "Could not reach the docx tool bridge." } });
  }
}

const S = tool.schema;

export const Docx = async () => ({
  tool: {
    create_docx: tool({
      description: "Create a REAL Microsoft Word (.docx) file from a structured spec. ALWAYS use this tool — never the plain 'write' tool — for ANY request to produce a .docx / Word document (report, memo, letter, template). 'write' only emits text and produces a corrupt file Word cannot open. 'path' is the workspace-relative target and MUST end in .docx. Build the document from ordered 'sections' (each with an optional heading, paragraphs, a bulleted/ordered list, and/or a table). Requires user permission approval.",
      args: {
        path: S.string(),
        title: S.string().optional(),
        sections: S.array(
          S.object({
            heading: S.object({ text: S.string(), level: S.number() }).optional(),
            paragraphs: S.array(S.object({ text: S.string(), bold: S.boolean().optional(), italic: S.boolean().optional() })).optional(),
            list: S.object({ ordered: S.boolean(), items: S.array(S.string()) }).optional(),
            table: S.object({ rows: S.array(S.array(S.string())) }).optional(),
          }),
        ),
      },
      async execute(args, ctx) {
        return call("create_docx", args, ctx);
      },
    }),
  },
});
`;

/** Write `<configDir>/plugin/docx.ts`. Refuses if the (static) source unexpectedly contains `forbidden`. */
export function writeDocxPlugin(configDir: string, forbidden?: string): void {
  if (forbidden !== undefined && forbidden.length > 0 && DOCX_PLUGIN_SOURCE.includes(forbidden)) {
    throw new Error("docx-plugin-file: refusing to write plugin containing a secret value");
  }
  const target = join(configDir, "plugin", "docx.ts");
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, DOCX_PLUGIN_SOURCE, "utf8");
}
