/**
 * MS365 OpenCode plugin bridge (CGHC MS365 P5.5, Task 3).
 *
 * `MS365_PLUGIN_SOURCE` is a STATIC string of TypeScript that runs inside OpenCode's in-process
 * Bun runtime (the pinned binary embeds Bun; a plugin file under `<configDir>/plugin/*.ts` is
 * loaded and executed directly — see the CGHC-028 version survey). It must never contain a
 * literal endpoint/token: both are read from `process.env` at plugin-load time inside the child
 * process, which the supervisor populates per-launch. This keeps the loopback boundary, the
 * token, and the tool surface entirely out of any file/log the product writes.
 *
 * The tool names below MUST match `TOOL_NAMES` in `../ms365/ms365-tool-router.ts` exactly —
 * `service/tests/ms365-plugin-file.test.ts` asserts this so router and plugin cannot drift.
 *
 * `writeMs365Plugin` mirrors the secret-refusal guard already used by `writeOpencodeConfig`
 * (opencode-config.ts): both accept an optional `forbidden` value and refuse to write if the
 * serialized output unexpectedly contains it. Because the plugin source here is a static
 * template with no interpolation, that branch should never trip — it exists as a regression
 * guard rather than a live code path.
 *
 * `seedMs365PluginDeps` copies `@opencode-ai/plugin` and its transitive `dependencies` (per its
 * own `package.json`: `@opencode-ai/sdk`, `@ai-sdk/provider`, `effect`, `zod` at the time this was
 * written) into `<configDir>/node_modules/` so the plugin's `import { tool } from
 * "@opencode-ai/plugin"` resolves offline. OpenCode otherwise background-installs the package via
 * npm the first time a config directory references a plugin, which requires network access this
 * product cannot assume is available. A missing source directory only logs a warning — it must
 * never throw, since OpenCode's own install is a fallback path.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const MS365_PLUGIN_SOURCE = `// AUTO-GENERATED by Cowork GHC — do not edit. Regenerated on every launch.
// Bridges OpenCode tool calls to the Cowork service MS365 boundary (loopback, scoped token).
import { tool } from "@opencode-ai/plugin";

const ENDPOINT = process.env["CGHC_MS365_TOOL_ENDPOINT"];
const TOKEN = process.env["CGHC_MS365_TOKEN"];

async function call(name, args, ctx) {
  if (!ENDPOINT || !TOKEN) {
    return JSON.stringify({ ok: false, error: { kind: "not_configured", message: "MS365 tool bridge is not configured in this session." } });
  }
  try {
    const res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "content-type": "application/json", "x-cowork-token": TOKEN },
      body: JSON.stringify({ name, args, sessionId: ctx.sessionID, requestId: crypto.randomUUID() }),
    });
    const body = await res.json();
    // Boundary envelope: { ok: true, data: ToolResult } | { ok: false, error: {...} }
    if (body && body.ok === true) return JSON.stringify(body.data);
    return JSON.stringify({ ok: false, error: { kind: "boundary_error", message: "MS365 boundary returned HTTP " + res.status + "." } });
  } catch {
    return JSON.stringify({ ok: false, error: { kind: "network_error", message: "Could not reach the MS365 tool bridge." } });
  }
}

const S = tool.schema;

// The scoped child token only reaches /v1/ms365/tool-call; the router's Ms365SessionScope is the
// real, fail-closed guard (Layer 2) — the child process cannot read its own session scope, so this
// hook deliberately does not gate anything today. MS365_TOOLS is a RESERVED SEAM: if the child ever
// learns its own scope, "tool.execute.before" below could turn this into an early, friendly block
// (fail fast in-process instead of round-tripping to the router for a session that will be
// rejected). Until then it is a no-op passthrough for every session, MS365-scoped or not.
const MS365_TOOLS = new Set([
  "sharepoint_search",
  "sharepoint_list_site_files",
  "sharepoint_get_file_summary",
  "sharepoint_upload_file",
  "ms365_list_joined_sites",
  "outlook_search_messages",
  "outlook_get_message",
  "outlook_summarize_message",
  "planner_list_plans",
  "planner_list_tasks",
  "planner_create_task",
  "planner_create_tasks",
  "planner_edit_task",
  "planner_delete_task",
  "lists_get_lists",
  "lists_get_items",
  "lists_add_item",
  "lists_edit_item",
  "lists_delete_item",
  "teams_list_chats",
  "teams_list_teams",
  "teams_list_channels",
  "teams_list_members",
  "teams_get_messages",
  "teams_post_message",
  "calendar_list_events",
  "calendar_search_events",
  "calendar_create_event",
  "onedrive_search_files",
  "onedrive_list_folder",
  "power_automate_list_flows",
  "power_automate_trigger_flow",
  "resolve_user",
  "get_me",
]);

export const Ms365 = async () => ({
  "tool.execute.before": async (input, output) => {
    if (!MS365_TOOLS.has(input.tool)) return;
    // No-op passthrough: this seam intentionally does not gate. The child process has no way to
    // know whether its own session is MS365-scoped, so any decision made here would be a guess.
    // The call always proceeds to the router, which is the actual authorization boundary and
    // fail-closes (rejects) for any session that is not MS365-scoped.
    return;
  },
  tool: {
    sharepoint_search: tool({ description: "Search SharePoint files by name/content. Site allowlist enforced server-side.", args: { query: S.string() }, async execute(args, ctx) { return call("sharepoint_search", args, ctx); } }),
    sharepoint_list_site_files: tool({ description: "List files in a SharePoint site drive root.", args: { siteId: S.string() }, async execute(args, ctx) { return call("sharepoint_list_site_files", args, ctx); } }),
    sharepoint_get_file_summary: tool({ description: "Read bounded text content of a SharePoint file for summarizing.", args: { driveItemId: S.string() }, async execute(args, ctx) { return call("sharepoint_get_file_summary", args, ctx); } }),
    sharepoint_upload_file: tool({ description: "Upload a workspace-local file to a SharePoint site. Requires user permission approval.", args: { siteId: S.string(), relativeLocalPath: S.string(), targetName: S.string() }, async execute(args, ctx) { return call("sharepoint_upload_file", args, ctx); } }),
    ms365_list_joined_sites: tool({ description: "List SharePoint sites the connected account follows, with enabled/disabled search scope.", args: {}, async execute(args, ctx) { return call("ms365_list_joined_sites", args, ctx); } }),
    outlook_search_messages: tool({ description: "Search Outlook mail (KQL query). Read-only.", args: { query: S.string() }, async execute(args, ctx) { return call("outlook_search_messages", args, ctx); } }),
    outlook_get_message: tool({ description: "Get one Outlook message by id (bounded body).", args: { id: S.string() }, async execute(args, ctx) { return call("outlook_get_message", args, ctx); } }),
    outlook_summarize_message: tool({ description: "Get bounded plain text of one Outlook message for summarizing.", args: { id: S.string() }, async execute(args, ctx) { return call("outlook_summarize_message", args, ctx); } }),
    planner_list_plans: tool({ description: "List the user's Planner plans (find a plan by name before acting; ask the user if ambiguous).", args: {}, async execute(args, ctx) { return call("planner_list_plans", args, ctx); } }),
    planner_list_tasks: tool({ description: "List tasks of a Planner plan (includes dueDateTime, percentComplete, etag).", args: { planId: S.string() }, async execute(args, ctx) { return call("planner_list_tasks", args, ctx); } }),
    planner_create_task: tool({ description: "Create ONE Planner task. Requires user permission approval per call.", args: { planId: S.string(), title: S.string(), dueDateTime: S.string().optional(), assigneeUserIds: S.array(S.string()).optional() }, async execute(args, ctx) { return call("planner_create_task", args, ctx); } }),
    planner_edit_task: tool({ description: "Edit a Planner task. MUST pass the exact etag from a fresh planner_list_tasks read.", args: { taskId: S.string(), etag: S.string(), title: S.string().optional(), dueDateTime: S.string().optional(), percentComplete: S.number().optional() }, async execute(args, ctx) { return call("planner_edit_task", args, ctx); } }),
    planner_delete_task: tool({ description: "Delete a Planner task. MUST pass the exact etag from a fresh read.", args: { taskId: S.string(), etag: S.string() }, async execute(args, ctx) { return call("planner_delete_task", args, ctx); } }),
    planner_create_tasks: tool({ description: "Create up to 20 Planner tasks in ONE user approval. If it returns kind=manual_mode, fall back to planner_create_task per item and tell the user why.", args: { planId: S.string(), tasks: S.array(S.object({ title: S.string(), dueDateTime: S.string().optional(), assigneeUserIds: S.array(S.string()).optional() })) }, async execute(args, ctx) { return call("planner_create_tasks", args, ctx); } }),
    lists_get_lists: tool({ description: "List SharePoint Lists of a site (find a list by name; ask the user if ambiguous).", args: { siteId: S.string() }, async execute(args, ctx) { return call("lists_get_lists", args, ctx); } }),
    lists_get_items: tool({ description: "Read items of a SharePoint List. Optional OData $filter (value only).", args: { siteId: S.string(), listId: S.string(), filter: S.string().optional() }, async execute(args, ctx) { return call("lists_get_items", args, ctx); } }),
    lists_add_item: tool({ description: "Add one item to a SharePoint List. Requires user permission approval.", args: { siteId: S.string(), listId: S.string(), fields: S.record(S.string(), S.unknown()) }, async execute(args, ctx) { return call("lists_add_item", args, ctx); } }),
    lists_edit_item: tool({ description: "Edit fields of a SharePoint List item. Requires user permission approval.", args: { siteId: S.string(), listId: S.string(), itemId: S.string(), fields: S.record(S.string(), S.unknown()) }, async execute(args, ctx) { return call("lists_edit_item", args, ctx); } }),
    lists_delete_item: tool({ description: "Delete a SharePoint List item. Requires user permission approval.", args: { siteId: S.string(), listId: S.string(), itemId: S.string() }, async execute(args, ctx) { return call("lists_delete_item", args, ctx); } }),
    teams_list_chats: tool({ description: "List the user's Teams chats (topic + members). If the group/chat the user asked for is NOT in the result, do not stop — check power_automate_list_flows for a configured flow whose description matches that target and use it instead.", args: {}, async execute(args, ctx) { return call("teams_list_chats", args, ctx); } }),
    teams_list_teams: tool({ description: "List joined Teams (Graph). If the team/group the user asked for is NOT in the result, do not stop — check power_automate_list_flows for a configured flow whose description matches that target and use it instead.", args: {}, async execute(args, ctx) { return call("teams_list_teams", args, ctx); } }),
    teams_list_channels: tool({ description: "List channels of a team.", args: { teamId: S.string() }, async execute(args, ctx) { return call("teams_list_channels", args, ctx); } }),
    teams_list_members: tool({ description: "List members of a chat OR a team (exactly one of chatId/teamId) — resolves userId for mentions/assignments.", args: { chatId: S.string().optional(), teamId: S.string().optional() }, async execute(args, ctx) { return call("teams_list_members", args, ctx); } }),
    teams_get_messages: tool({ description: "Get recent messages of a chat (chatId) or channel (teamId+channelId). No server-side search — filter client-side.", args: { chatId: S.string().optional(), teamId: S.string().optional(), channelId: S.string().optional() }, async execute(args, ctx) { return call("teams_get_messages", args, ctx); } }),
    teams_post_message: tool({ description: "Post a Teams message to a chat (chatId) or channel (teamId+channelId) via Graph. Use this only for teams/chats found via teams_list_teams/teams_list_chats. If the requested team/chat/group cannot be found there, do NOT give up — first check power_automate_list_flows for a configured flow whose description matches that target group and trigger it instead. Mentions: use @{i} placeholders in content with mentions[i]={userId,displayName}. Requires user permission approval.", args: { chatId: S.string().optional(), teamId: S.string().optional(), channelId: S.string().optional(), content: S.string(), mentions: S.array(S.object({ userId: S.string(), displayName: S.string() })).optional() }, async execute(args, ctx) { return call("teams_post_message", args, ctx); } }),
    calendar_list_events: tool({ description: "List Outlook calendar events in a time window (ISO 8601 start/end). Read-only.", args: { start: S.string(), end: S.string() }, async execute(args, ctx) { return call("calendar_list_events", args, ctx); } }),
    calendar_search_events: tool({ description: "Search Outlook calendar events by free-text query. Read-only.", args: { query: S.string() }, async execute(args, ctx) { return call("calendar_search_events", args, ctx); } }),
    calendar_create_event: tool({ description: "Create an Outlook calendar event (optionally an online Teams meeting). ISO 8601 start/end; timezone defaults to UTC. Requires user permission approval.", args: { subject: S.string(), start: S.string(), end: S.string(), attendees: S.array(S.string()).optional(), online: S.boolean().optional(), timezone: S.string().optional() }, async execute(args, ctx) { return call("calendar_create_event", args, ctx); } }),
    onedrive_search_files: tool({ description: "Search the connected account's personal OneDrive by name/content. Read-only.", args: { query: S.string() }, async execute(args, ctx) { return call("onedrive_search_files", args, ctx); } }),
    onedrive_list_folder: tool({ description: "List children of a personal OneDrive folder (root when itemId omitted). Read-only.", args: { itemId: S.string().optional() }, async execute(args, ctx) { return call("onedrive_list_folder", args, ctx); } }),
    power_automate_list_flows: tool({ description: "List configured Power Automate flows (name + description + payloadSchema). Flows may target Teams channels, groups, email, etc. that are NOT reachable via the Graph teams_/outlook_ tools — whenever a Graph lookup does not find a requested named group/team/target, ALWAYS check here for a matching flow before concluding the action is impossible. Read each description to decide when to call a flow, and read its payloadSchema (a JSON Schema) to build a conformant payload from the user's request, then call power_automate_trigger_flow by name with that payload.", args: {}, async execute(args, ctx) { return call("power_automate_list_flows", args, ctx); } }),
    power_automate_trigger_flow: tool({ description: "Trigger a configured Power Automate flow by its 'name' (preferred — resolves the URL server-side, refuses disabled flows) or by raw 'url', with an optional JSON payload. Returns the flow's HTTP status and response body. Requires user permission approval.", args: { name: S.string().optional(), url: S.string().optional(), payload: S.unknown().optional() }, async execute(args, ctx) { return call("power_automate_trigger_flow", args, ctx); } }),
    resolve_user: tool({ description: "Resolve people by name or email to user ids (needed before mention/assign/invite). Read-only.", args: { query: S.string() }, async execute(args, ctx) { return call("resolve_user", args, ctx); } }),
    get_me: tool({ description: "Get the connected account's own identity (display name, mail, time zone). Read-only.", args: {}, async execute(args, ctx) { return call("get_me", args, ctx); } }),
  },
});
`;

/** Write `<configDir>/plugin/ms365.ts`. Refuses if the (static) source unexpectedly contains `forbidden`. */
export function writeMs365Plugin(configDir: string, forbidden?: string): void {
  if (forbidden !== undefined && forbidden.length > 0 && MS365_PLUGIN_SOURCE.includes(forbidden)) {
    throw new Error("ms365-plugin-file: refusing to write plugin containing a secret value");
  }
  const target = join(configDir, "plugin", "ms365.ts");
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, MS365_PLUGIN_SOURCE, "utf8");
}

/**
 * Copy `@opencode-ai/plugin` (+ its declared `dependencies`, recursively) from `nodeModulesRoot`
 * into `<configDir>/node_modules` so the plugin's import resolves offline — independent of
 * OpenCode's own background `npm install` (which needs network). A missing source package only
 * logs a warning (via the caller-redacted `log` sink) and is skipped; OpenCode's own install
 * remains the fallback.
 */
export function seedMs365PluginDeps(
  configDir: string,
  nodeModulesRoot: string,
  log: (m: string) => void,
): void {
  const targetRoot = join(configDir, "node_modules");
  const copied = new Set<string>();
  const copyPkg = (name: string): void => {
    if (copied.has(name)) return;
    copied.add(name);
    const src = join(nodeModulesRoot, ...name.split("/"));
    if (!existsSync(src)) {
      log(`ms365_plugin_seed_missing pkg=${name}`);
      return;
    }
    try {
      cpSync(src, join(targetRoot, ...name.split("/")), { recursive: true });
    } catch {
      log(`ms365_plugin_seed_copy_failed pkg=${name}`);
      return;
    }
    try {
      const pkg = JSON.parse(readFileSync(join(src, "package.json"), "utf8")) as {
        dependencies?: Record<string, string>;
      };
      for (const dep of Object.keys(pkg.dependencies ?? {})) copyPkg(dep);
    } catch {
      log(`ms365_plugin_seed_pkgjson_unreadable pkg=${name}`);
    }
  };
  copyPkg("@opencode-ai/plugin");
}
