/**
 * The shared remote-pairing content: reachable URLs, a one-time pairing code + scannable QR,
 * and the paired-device list. Rendered by both the `/remote` overlay (remote-panel.ts) and the
 * Dispatch surface, so the two cannot drift apart.
 *
 * It is a THIN client of `/v1/remote`: it holds no state beyond what it just fetched, renders
 * no secret (the QR encodes only a one-time pairing URL), and enforces nothing — the service
 * owns the pairing registry and the gateway. When remote is off it says so honestly rather
 * than pretending a gateway exists.
 */

import type { RemoteStatus, RemotePairingCode } from "./service-client.js";
import { el } from "./ui-shell/dom-utils.js";

/** The minimal client surface pairing needs (a subset of the full ServiceClient). */
export interface RemotePairingClient {
  remoteStatus(): Promise<RemoteStatus>;
  remoteIssuePairingCode(): Promise<RemotePairingCode>;
  remoteRevokeAll(): Promise<void>;
}

export interface RemotePairingOptions {
  /** Called after a successful revoke-all so the host can re-render itself. */
  readonly onRevoked?: () => void;
  /** Omit the device list + revoke control (the Dispatch surface keeps it compact). */
  readonly hideDevices?: boolean;
}

function renderUrls(status: RemoteStatus): HTMLElement {
  // LAN first — those are the ones a phone can actually reach.
  const urls = [...status.lanUrls, ...(status.url !== null ? [status.url] : [])];
  const section = el("div", "remote-section");
  section.appendChild(el("div", "remote-section__label", "Địa chỉ mở trên điện thoại"));
  for (const url of urls) section.appendChild(el("div", "remote-url", url));
  if (urls.length === 0) {
    section.appendChild(el("p", "remote-note", "Chỉ loopback — mở qua Tailscale/VPN của bạn."));
  }
  return section;
}

/**
 * The QR SVG is generated by our own service (the `qrcode` lib) and encodes only a one-time
 * pairing URL, so it should hold nothing but shapes. Parse and adopt it rather than assigning
 * innerHTML: a QR code does not justify an HTML-injection sink in the renderer. Anything
 * carrying script, foreignObject, or an event-handler attribute is refused outright.
 */
function adoptQrSvg(holder: HTMLElement, svgText: string): boolean {
  const parsed = new DOMParser().parseFromString(svgText, "image/svg+xml");
  if (parsed.querySelector("parsererror") !== null) return false;
  const svg = parsed.documentElement;
  if (svg.tagName.toLowerCase() !== "svg") return false;
  if (svg.querySelector("script, foreignObject") !== null) return false;
  for (const node of [svg, ...Array.from(svg.querySelectorAll("*"))]) {
    for (const attr of Array.from(node.attributes)) {
      if (attr.name.toLowerCase().startsWith("on")) return false;
    }
  }
  holder.replaceChildren(document.importNode(svg, true));
  return true;
}

function renderPairing(client: RemotePairingClient): HTMLElement {
  const section = el("div", "remote-section");
  section.appendChild(el("div", "remote-section__label", "Ghép nối thiết bị"));

  const codeRow = el("div", "remote-code-row");
  const codeValue = el("div", "remote-code", "········");
  const issueBtn = el("button", "remote-btn", "Tạo mã ghép nối");
  const qrHolder = el("div", "remote-qr");
  const note = el("p", "remote-note", "");

  issueBtn.addEventListener("click", () => {
    issueBtn.disabled = true;
    note.textContent = "";
    void client
      .remoteIssuePairingCode()
      .then((issued: RemotePairingCode) => {
        codeValue.textContent = issued.code;
        qrHolder.replaceChildren();
        const shown = issued.qrSvg !== null && adoptQrSvg(qrHolder, issued.qrSvg);
        note.textContent = shown
          ? "Mã dùng 1 lần, hết hạn sau 2 phút. Quét QR hoặc nhập mã trên điện thoại."
          : "Mã dùng 1 lần, hết hạn sau 2 phút. Nhập mã trên điện thoại (không dựng được QR).";
      })
      .catch(() => {
        note.textContent = "Không tạo được mã — thử lại.";
      })
      .finally(() => {
        issueBtn.disabled = false;
      });
  });

  codeRow.appendChild(codeValue);
  codeRow.appendChild(issueBtn);
  section.appendChild(codeRow);
  section.appendChild(qrHolder);
  section.appendChild(note);
  return section;
}

function renderDevices(
  client: RemotePairingClient,
  status: RemoteStatus,
  onRevoked?: () => void,
): HTMLElement {
  const section = el("div", "remote-section");
  section.appendChild(el("div", "remote-section__label", "Thiết bị đã ghép nối"));
  if (status.devices.length === 0) {
    section.appendChild(el("p", "remote-note", "Chưa có thiết bị nào."));
    return section;
  }
  for (const device of status.devices) {
    const row = el("div", "remote-device");
    row.appendChild(el("span", "remote-device__name", device.name));
    row.appendChild(el("span", "remote-device__meta", device.deviceId));
    section.appendChild(row);
  }
  const revokeBtn = el("button", "remote-btn remote-btn--danger", "Thu hồi tất cả (/remote off)");
  revokeBtn.addEventListener("click", () => {
    revokeBtn.disabled = true;
    void client
      .remoteRevokeAll()
      .then(() => onRevoked?.())
      .catch(() => {
        revokeBtn.disabled = false;
      });
  });
  section.appendChild(revokeBtn);
  return section;
}

/**
 * Replace `body` with the current remote-pairing state. Never throws: a service that is not
 * reachable, or a gateway that is off, renders an honest explanation instead.
 */
export async function renderRemotePairing(
  client: RemotePairingClient,
  body: HTMLElement,
  options: RemotePairingOptions = {},
): Promise<void> {
  let status: RemoteStatus;
  try {
    status = await client.remoteStatus();
  } catch {
    body.replaceChildren(
      el(
        "p",
        "remote-note",
        "Điều phối từ xa chưa sẵn sàng trong phiên này. Hãy mở lại ứng dụng bằng lối tắt Cowork GHC để bật cổng kết nối từ xa.",
      ),
    );
    return;
  }

  if (!status.enabled) {
    body.replaceChildren(
      el(
        "p",
        "remote-note",
        "Cổng kết nối từ xa chưa bật trong phiên này. Hãy mở lại ứng dụng bằng lối tắt Cowork GHC để bật.",
      ),
    );
    return;
  }

  const parts: HTMLElement[] = [renderUrls(status), renderPairing(client)];
  if (options.hideDevices !== true) {
    parts.push(renderDevices(client, status, options.onRevoked));
  }
  body.replaceChildren(...parts);
}
